---
# tasks file for docker-centos
- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Add Docker-ce repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker-ce
  package:
    name: docker-ce
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
